### ISSUE TITLE
Home button always visibale

### ISSUE THREAD

**Issue by hajdenrajch-m** [Redundakitties/colorful-minimalist#4]
I am using the latest Sidebery beta. When the menu is collapsed, the title bar of the Sidebery is visible.
I am using the latest Firefox: 111.0 64bit
![image](https://user-images.githubusercontent.com/69001987/226061829-72ab920a-ebe8-4cda-a621-cdd184de69c9.png)

**Comment by hajdenrajch-m** [comment]
A quick and dirty solution.

```
/* Hide Sidebery Header */
#main-window:not([extradragspace="true"])
    #sidebar-header {
		visibility: hidden;
		display: none
}
```

**Comment by Redundakitties** [comment]
In my [userchrome](https://github.com/Redundakitties/colorful-minimalist/blob/main/userChrome.css#L22) file I have:

```
#TabsToolbar, #sidebar-header, #sidebar-splitter {
  display: none;
}
```
So the sidebar header is by default hidden. I turned back on its visibility to try and debug this problem, but for some reason I can't unset its width so that it would grow and shrink with the rest of the sidebar. I'll keep working on it though, (if you wanted to switch to the right hand [sidebery mods](https://github.com/Redundakitties/colorful-minimalist/blob/main/hacks/sideberyMods.css) it works on that side because the bar isn't growing or shrinking, it's just being shoved off screen).

**Comment by Redundakitties** [comment]
okay, this is really jank solution, but in the hypothetical situation where you REALLY want to use the sidebar header when the sidebar is extended, here's a bit of strange code that will work. 

```css
/* hide header stuff when collapsed */
#sidebar-box .close-icon,
#sidebar-box .tabbable #sidebar-switcher-arrow {
    opacity: 0% !important;
    transition: all 0.2s ease-in-out;
}
#sidebar-box .tabbable label {
    width: 0px;
    transition: all 0.2s ease-in-out;
}

/* show header stuff when extended */
#sidebar-box:hover .tabbable label,
#sidebar-box:hover {
    /* tweak this width to your liking */
    width: calc(var(--autohide-sidebar-extended) - var(--autohide-sidebar-collapsed)*2);
}
#sidebar-box:hover .close-icon, 
#sidebar-box:hover .tabbable #sidebar-switcher-arrow {
    opacity: 100% !important;
}
```
there are issues here, namely that it's hard to see the close and switch button when the sidebar is extended, but I'm not really sure how to fix that. If you uncomment this section from in sideberymodsLeft: 

```css
/* width of panel (grey box) on hover */
/* uncomment this section if you want the webpage to move when your tabs are extended- otherwise covers */ 
#main-window:not([extradragspace="true"])
    #sidebar-box[sidebarcommand="_3c078156-979c-498b-8990-85f7987dd929_-sidebar-action"]:not([hidden]):hover {
    width: var(--autohide-sidebar-extended) !important;
    min-width: unset !important;
    z-index: 1;
}
```
It will properly give those buttons a background... but not in a way that's really appealing. 

Feel free to do your own experimentation, I also like adding this bit: 
```css
#sidebar-box .tabbable {
    margin-left: -4px !important;
}
```
to better align the sidebery icon.

**Comment by Redundakitties** [comment]
final block of code (adds a background color to .tabbable so that it's clearer to see):
```css

#sidebar-box .close-icon,
#sidebar-box .tabbable #sidebar-switcher-arrow {
    opacity: 0% !important;
    transition: all 0.2s ease-in-out;
}
#sidebar-box .tabbable label {
    width: 0px;
    transition: all 0.2s ease-in-out;
}
#sidebar-box .tabbable {
    margin-left: -4px !important;
    transition: all 0.2s ease-in-out;
}

/* show header stuff when extended */
#sidebar-box:hover .tabbable label,
#sidebar-box:hover {
    /* tweak this width to your liking */
    width: calc(var(--autohide-sidebar-extended) - var(--autohide-sidebar-collapsed)*2);
}
#sidebar-box:hover .close-icon, 
#sidebar-box:hover .tabbable #sidebar-switcher-arrow,
#sidebar-box:hover .tabbable {
    opacity: 100% !important;
    background-color: var(--lwt-accent-color) !important;
}
```
