### ISSUE TITLE
 Sidebery beta v5  Tab colors --hover-bg won't work

### ISSUE THREAD

**Issue by Judefy** [Redundakitties/colorful-minimalist#5]
I installed  sidebery beta v5, used your [sideberyTweaksv5],but Tab colors --hover-bg won't work

**Comment by Redundakitties** [comment]
oof, thank you for bringing this to my attention! I have no idea when that changed, I just completely didn't notice. Looks like sidebery's CSS elements changed, I'll have to update them to match.

**Comment by Judefy** [comment]
> oof, thank you for bringing this to my attention! I have no idea when that changed, I just completely didn't notice. Looks like sidebery's CSS elements changed, I'll have to update them to match.

 I'm looking forward to it.

**Comment by Redundakitties** [comment]
add this to your css instead of hover-bg:

```css
.Tab[title*="https://github.com"], 
.PinnedTab[title*="https://github.com"] {
	--tabs-activated-bg: var(--white); /* current background */
}
.Tab[title*="https://github.com"]:hover { 
	--frame-el-bg: var(--white); /* --hover-bg */
}
```

it's just a workaround for now, as far as I can tell though it seems like the variable got deleted from sidebery :/

**Comment by Judefy** [comment]
> 
This is very good！Have a wonderful day！

**Comment by Judefy** [comment]
> add this to your css instead of hover-bg:
> 
> ```css
> .Tab[title*="https://github.com"], 
> .PinnedTab[title*="https://github.com"] {
> 	--tabs-activated-bg: var(--white); /* current background */
> }
> .Tab[title*="https://github.com"]:hover { 
> 	--frame-el-bg: var(--white); /* --hover-bg */
> }
> ```
> 
> it's just a workaround for now, as far as I can tell though it seems like the variable got deleted from sidebery :/

This is very good！Have a wonderful day！

**Comment by Redundakitties** [comment]
my friend let me know of a better fix, just use this instead (much cleaner): 👍

```css
.Tab[title*="https://github.com"], 
.PinnedTab[title*="https://github.com"] {
	--tabs-activated-bg: var(--white); /* current background */
	--frame-el-overlay-hover-bg: var(--white); /* hover bg */
}
```
