### ISSUE TITLE
Scroll tab title based on content width

### ISSUE THREAD

**Issue by FynnFreyer** [Redundakitties/colorful-minimalist#6]
Hi, I saw your v2 post on Reddit, and I love what you did!

It would be nice if the tab titles didn't scroll a fixed amount, but based on the title length.

I've rigged something up, that works for me, maybe you want to have a look. It's not super nice though, because I'm just not good with CSS. This does nothing if the title doesn't overflow, but it scrolls the appropriate amount if it does.

```css
:root {
  --nav-width: 40px;
  --fav-horiz-margin: 13px;
  --fav-width: 16px;
  --close-width: 31px;

  --min-tab-offset: calc(var(--nav-width)
                        + var(--fav-horiz-margin)
                        + var(--fav-width));
  --min-margin-correction: calc(100vw
                                - var(--min-tab-offset)
                                - 100%);
}

div.NavigationBar {
  width: var(--nav-width);
}

div.panel-btn {
  width: var(--nav-width) !important;
  height: var(--nav-width) !important;
}

.Tab .t-box {
  min-width: fit-content;
}

.Tab .t-box .title {
  transition: all 1.5s ease;
  display: inline-block;
}

.Tab:hover .title {
  margin-left: min(var(--min-margin-correction) , 0px);
}

.Tab[data-lvl="1"]:hover .title {
  --margin-correction: calc(var(--min-margin-correction)
                            - var(--tabs-indent));

  margin-left: min(var(--margin-correction) , 0px);
}

.Tab[data-lvl="2"]:hover .title {
  --margin-correction: calc(var(--min-margin-correction)
                            - (var(--tabs-indent) * 2));

  margin-left: min(var(--margin-correction) , 0px);
}
```

This is what I came up with, based on your work. Unfortunately, it needs dedicated rules for each indent level. The `.NavigationBar` and `.panel-btn` styling is not necessary, but it's important to know the value to calculate the appropriate offset.

There are some issues with this. It would be nice to work the `--close-width` in there as well, and generally I hard-coded stuff that probably shouldn't be.

Kind regards, and thanks for your work.

**Comment by Redundakitties** [comment]
This is very amusing! Thank you for making this :) It was something I had wanted to do but never got around to messing with.
What's the difference between including the dedicated rules for each indent and not? 
This is what mine looks like with just these rules: 

```css
#root.root {
  --nav-width: 40px;
  --fav-horiz-margin: 13px;
  --fav-width: 16px;
  --close-width: 31px;

  --min-tab-offset: calc(var(--nav-width)
                        + var(--fav-horiz-margin)
                        + var(--fav-width));
  --min-margin-correction: calc(100vw
                                - var(--min-tab-offset)
                                - 100%);
}
/* ----------- Tab title styles ----------- */

div.NavigationBar {
  width: var(--nav-width);
}

.Tab .t-box {
  min-width: fit-content;
}

.Tab .t-box .title {
  transition: all 1.5s ease;
  display: inline-block;
}

.Tab:hover .title {
  margin-left: min(var(--min-margin-correction) , 0px);
}
```

https://user-images.githubusercontent.com/38409600/233097426-13574aa5-e7c2-4a58-b587-c54ba9e832d8.mp4

**Comment by Redundakitties** [comment]
ah I see why now! (Also added `--close-width` to `var( --min-margin-correction)` and I see the difference more clearly now. 

Is there no way to somehow use `var(--tabs-indent)` to automatically calculate it per level?

**Comment by FynnFreyer** [comment]
I was looking for a way to do that too, but unfortunately you can only access `attr(data-lvl)` on the tab. I tried something with `.Tab[data-lvl]:nth-child(1):nth-child(4)`, but couldn't get it to work =(

I have set my max indent level to three, so this suffices, but I know, this is ugly as hell =/

**Comment by FynnFreyer** [comment]
Might look into it another day, but I spend 5 h styling my tab bar today, and I'm over it

**Comment by Redundakitties** [comment]
Mood 😵‍💫

**Comment by Redundakitties** [comment]
Using this:
```css
.Tab .title {
  display: inline-block;
  vertical-align: top;
  transition: transform 5s linear;
} 

.Tab:hover .title { transform: translateX(-100%); }
```

it now looks like this:

https://user-images.githubusercontent.com/38409600/234785411-8ddd3472-362f-47e1-86fa-2078683eec00.mp4

timing can be played with, so can the transition effect if you want ease instead of linear. However, I'm still unsure how to work in --close-width. Changing the transform to something like: `translateX(calc(-100% + 135px)); ` works but only for data-lvl="1" tabs as you might expect. Becoming worse and worse as the nests continue. There _must_ be a way to calculate the width of each tab dynamically as the nesting continues but I haven't found it yet. 

Anyway, despite that small failure I hope this snippet might be useful to you, if you're still in any mood to continue tweaking sidebery.

**Comment by jathek** [comment]
Just a thought, but I include the below in my Sidebery style specifically so I can write styles that calculate by tree level for any child element of a tab.
```css
  .Tab[data-lvl="0"], .pointer[data-lvl="0"] { --tree-lvl: 0; }
  .Tab[data-lvl="1"], .pointer[data-lvl="1"] { --tree-lvl: 1; }
  .Tab[data-lvl="2"], .pointer[data-lvl="2"] { --tree-lvl: 2; }
  .Tab[data-lvl="3"], .pointer[data-lvl="3"] { --tree-lvl: 3; }
  .Tab[data-lvl="4"], .pointer[data-lvl="4"] { --tree-lvl: 4; }
  .Tab[data-lvl="5"], .pointer[data-lvl="5"] { --tree-lvl: 5; }
  .Tab[data-lvl="6"], .pointer[data-lvl="6"] { --tree-lvl: 6; }
  .Tab[data-lvl="7"], .pointer[data-lvl="7"] { --tree-lvl: 7; }
  .Tab[data-lvl="8"], .pointer[data-lvl="8"] { --tree-lvl: 8; }
  .Tab[data-lvl="9"], .pointer[data-lvl="9"] { --tree-lvl: 9; }
  .Tab[data-lvl="10"], .pointer[data-lvl="10"] { --tree-lvl: 10; }
  .Tab[data-lvl="11"], .pointer[data-lvl="11"] { --tree-lvl: 11; }
```

So you could probably do something like:
```css
.Tab:hover .title {
  --margin-correction: calc(var(--min-margin-correction)
                            - var(--tabs-indent) * var(--tree-lvl));
```

**Comment by FynnFreyer** [comment]
That's a great idea! You still have to add those per level definitions, but this is much clearer and encapsulated

**Comment by jathek** [comment]
I've settled on this. Might need to be tweaked for other themes:

```css
  #root {
    --fav-size: 24px;
    --tabs-margin: 6px;
    --tabs-inner-gap: var(--tabs-margin);
    --scrollbar-size: 8px; /* thin scrollbars */
  }
  /* -------------- tree: tab title - scroll */
  /* ------- set t-box width and mask, declare title variables */
  .Tab .t-box,
  .ClosedTabsSubPanel .closed-tab .t-box {
    --non-title-elem-width-scroll: calc(var(--tabs-margin) * 2 + var(--tabs-inner-gap) * 3 + var(--fav-size) + var(--tabs-indent) * var(--tree-lvl) + var(--scrollbar-size));
    --non-title-elem-width: var(--non-title-elem-width-scroll);
    --visible-title-width: calc(100vw - var(--non-title-elem-width));
    width: var(--visible-title-width);
    min-width: fit-content;
    mask: linear-gradient(to right, #000 calc(var(--visible-title-width) - var(--tabs-inner-gap)), #0000 var(--visible-title-width));
  }
  /* ------- different non-title-elem-width for non-scrolling */
  .TabsPanel .top-shadow[data-show="false"] + .bottom-shadow[data-show="false"] + .scroll-container .Tab .t-box,
  .ClosedTabsSubPanel .top-shadow[data-show="false"] + .bottom-shadow[data-show="false"] + .scroll-container .closed-tab .t-box {
    --non-title-elem-width: calc(var(--non-title-elem-width-scroll) - var(--scrollbar-size));
  }
  /* ------- title animation, declare title offset */
  .Tab .t-box .title,
  .ClosedTabsSubPanel .closed-tab .t-box .title {
    --title-offset: calc(var(--visible-title-width) - 100%);
    transition: margin-left 1.5s 0.25s ease;
  }
  /* ------- remove mask when hovered */
  .Tab:hover .t-box,
  .ClosedTabsSubPanel .closed-tab:hover .t-box {
    mask: linear-gradient(to right, #000 var(--visible-title-width), #0000 var(--visible-title-width));
  }
  /* ------- offset title when hovered */
  .Tab:hover .t-box .title,
  .ClosedTabsSubPanel .closed-tab:hover .t-box .title {
    margin-left: min(var(--title-offset), 0px);
  }
```

looks like this:

https://user-images.githubusercontent.com/692914/235259614-7dd64a3c-fb1c-4403-8723-86d02eafa3e1.mp4

EDIT 2023-04-30: added rules for changing title width if scrollbar is visible

**Comment by sintapilgo** [comment]
Could someone please share the final code? It's working for me, but it's overlapping tab close button.

It should work like in [this](https://github.com/Redundakitties/colorful-minimalist/issues/6#issuecomment-1524929899) video from @Redundakitties, but I don't know which code was used.

**Comment by Redundakitties** [comment]
```css
.Tab .title {
  display: inline-block;
  vertical-align: top;
  transition: transform 6s linear;
} 

.Tab:hover .title { transform: translateX(-100%);} 
```
this? it's what im currently using at least. and cuz it just goes till it's out of sight it doesn't overlap with the close button

**Comment by jathek** [comment]
```css
  #root {
    --fav-size: 24px;
    --tabs-margin: 6px;
    --tabs-inner-gap: var(--tabs-margin);
    --scrollbar-size: 8px; /* thin scrollbars */
  }
  /* -------------- tree: tab title - scroll */
  /* ------- set t-box width and mask, declare title variables */
  .Tab .t-box,
  .ClosedTabsSubPanel .closed-tab .t-box {
    --non-title-elem-width-scroll: calc(var(--tabs-margin) * 2 + var(--tabs-inner-gap) * 3 + var(--fav-size) + var(--tabs-indent) * var(--tree-lvl) + var(--scrollbar-size));
    --non-title-elem-width: var(--non-title-elem-width-scroll);
    --visible-title-width: calc(100vw - var(--non-title-elem-width));
    width: var(--visible-title-width);
    min-width: fit-content;
    mask: linear-gradient(to right, #000 calc(var(--visible-title-width) - var(--tabs-inner-gap)), #0000 var(--visible-title-width)) !important;
  }
  /* ------- different non-title-elem-width for close button */
  #root[data-tabs-close-btn="always"] .Tab .t-box,
  #root[data-tabs-close-btn="hover"] .Tab:hover .t-box {
    --close-button-width: var(--fav-size) + var(--tabs-inner-gap);
    --non-title-elem-width-scroll: calc(var(--tabs-margin) * 2 + var(--tabs-inner-gap) * 3 + var(--fav-size) + var(--tabs-indent) * var(--tree-lvl) + var(--scrollbar-size) + var(--close-button-width));
  }
  /* ------- different non-title-elem-width for non-scrolling */
  .TabsPanel .top-shadow[data-show="false"] + .bottom-shadow[data-show="false"] + .scroll-container .Tab .t-box,
  .ClosedTabsSubPanel .top-shadow[data-show="false"] + .bottom-shadow[data-show="false"] + .scroll-container .closed-tab .t-box {
    --non-title-elem-width: calc(var(--non-title-elem-width-scroll) - var(--scrollbar-size));
  }
  /* ------- title animation, declare title offset */
  .Tab .t-box .title,
  .ClosedTabsSubPanel .closed-tab .t-box .title {
    --title-offset: calc(var(--visible-title-width) - 100%);
    transition: margin-left 1.5s 0.25s ease;
  }
  /* ------- remove mask when hovered, not selected, and context menu is inactive */
  .CtxMenu[data-active="false"] ~ .main-box .Tab[data-selected="false"]:hover .t-box,
  .ClosedTabsSubPanel .closed-tab:hover .t-box {
    mask: linear-gradient(to right, #000 var(--visible-title-width), #0000 var(--visible-title-width)) !important;
  }
  /* ------- offset title when hovered, not selected, and context menu is inactive */
   .CtxMenu[data-active="false"] ~ .main-box .Tab[data-selected="false"]:hover .t-box .title,
  .ClosedTabsSubPanel .closed-tab:hover .t-box .title {
    margin-left: min(var(--title-offset), 0px);
  }
```

Here's mine. I don't have infinite scroll but I have some alternate widths for when the close button is shown. You'll want to set `--close-button-width` to whatever you want. My close button is the same width as the favicon and then is offset from the right for one `tabs-inner-gap`.
